version: '1'
services:
  db:
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
